#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <time.h>

void selectionSortNumeros(int v[], int n) {
    for (int i = 0; i < n; i++) {
        int index_menor = i;
        for (int j = i + 1; j < n; j++) {
            if (v[j] < v[index_menor])
                index_menor = j;
        }
        int aux = v[i];
        v[i] = v[index_menor];
        v[index_menor] = aux;
    }
}

void selectionSortPalavras(char arr[][50], int n) {
    for (int i = 0; i < n - 1; i++) {
        int index_menor = i;
        for (int j = i + 1; j < n; j++) {
            if (strcmp(arr[j], arr[index_menor]) < 0) {
                index_menor = j;
            }
        }
        char temp[50];
        strcpy(temp, arr[i]);
        strcpy(arr[i], arr[index_menor]);
        strcpy(arr[index_menor], temp);
    }
}

int qntdNum = 100000;
int arrayNums[100000];
char palavras[8000][800] = {
    "amor", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo", "brisa", "chuva", "dado", "energia",
    "felicidade", "garrafa", "história", "infinito", "jasmim",
    "karisma", "lua", "montanha", "natureza", "oceano",
    "paz", "quintal", "raio", "sorriso", "tempo",
    "universo", "vento", "xícara", "youtuber", "zen",
    "azul", "baleia", "chocolate", "dúvida", "esperança",
    "futuro", "globo", "honra", "ideia", "jovem",
    "kilo", "livro", "música", "nuvem", "orquídea",
    "praia", "qualidade", "rosa", "sonho", "trilha",
    "união", "vida", "xampu", "yeti", "ziguezague",
    "anel", "bicicleta", "caderno", "diamante", "estrela",
    "fogão", "galáxia", "herói", "ilha", "janela",
    "kiwi", "limonada", "mapa", "navio", "olho",
    "palhaço", "quadro", "rio", "sol", "tigre",
    "urso", "violão", "xarope", "safira", "tartaruga",
    "unicórnio", "violino", "xilofone", "zoológico", "diamante",
    "papagaio", "quadrado", "relâmpago", "energia", "esperança",
    "montanha", "neve", "oceano", "lua", "internet",
    "cachorro", "girassol", "elefante", "diamante", "energia",
    "alegria", "bandeira", "coração", "desafio", "explosão",
    "floresta", "guitarra", "hipnotizar", "imaginário", "jogo",
    "kiwi", "luz", "mundo", "notícia", "olhar",
    "paz", "quarto", "rosa", "serpente", "tempestade",
    "unidade", "vulcão", "tigre", "xícara", "yoga",
    "zebra", "água", "brilho", "café", "dólar",
    "elefante", "fogo", "gelo", "hipopótamo", "inimigo",
    "jovem", "lava", "mágico", "nevoeiro", "orvalho",
    "ponto", "quimono", "rato", "sol", "touro",
    "uva", "viagem", "xampu", "zangado", "alvo",
    "banco", "capitão", "dólar", "elefante", "futuro",
    "galáxia", "horizonte", "invisível", "jogador", "kamikaze",
    "lenda", "mestre", "nuvem", "oceano", "pioneiro",
    "quente", "relâmpago", "solução", "trovoada", "universo",
    "vazio", "zangado", "abóbora", "beijo", "coração",
    "dourado", "esmeralda", "fogo", "glória", "herói",
    "isolado", "jovem", "kilo", "luz", "mistério",
    "neve", "olho", "piano", "quadro", "rápido",
    "sol", "tesouro", "urso", "vulcão", "xaxim",
    "yeti", "zelador", "alvo", "borboleta", "caverna",
    "diamante", "elétrico", "fumaça", "gelo", "halo"
};

// Função para criar números aleatórios
void criarNum() {
    for (int i = 0; i < qntdNum; i++) {
        arrayNums[i] = rand() % qntdNum;
    }
}

int main() {
    printf("---------------------------------------------------------------------------\n");
    printf("Voce deseja testar os metodos de ordenacao com numeros ou palavras?\n");
    printf("1 - Numeros\n2 - Palavras\n3 - Sair\n");
    printf("---------------------------------------------------------------------------\n");
    int resp;
    printf("Insira um numero: ");
    scanf("%d", &resp);

    if (resp == 1) {
        printf("Criando uma array de numeros aleatorios...\n");
        criarNum();

        clock_t start = clock();
        selectionSortNumeros(arrayNums, qntdNum);
        clock_t end = clock();

        double elapsed_time = ((double)(end - start)) / CLOCKS_PER_SEC;
        printf("Tempo de execucao do Selection Sort para numeros: %.6f segundos\n", elapsed_time);

    } else if (resp == 2) {
        clock_t start = clock();
        selectionSortPalavras(palavras, 8000);  // Algoritmo de ordenação
        clock_t end = clock();
        double tempo_execucao = (double)(end - start) / CLOCKS_PER_SEC;
        printf("Tempo de execucao do Selection Sort para palavras: %.6f segundos\n", tempo_execucao);


    } else if (resp == 3) {
        printf("Finalizando o programa!\n");
    } else {
        printf("Opcao invalida! Tente novamente.\n");
    }

    return 0;
}
